sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '7'
  - '6'
  - '4'
before_install:
  - "curl -o- -L https://yarnpkg.com/install.sh | bash"
  - "export PATH=\"$HOME/.yarn/bin:$PATH\""
#   - npm i -g npm@^2.0.0
# before_script:
#   # - npm prune
#   - "curl -o- -L https://yarnpkg.com/install.sh | bash"
#   - "export PATH=\"$HOME/.yarn/bin:$PATH\""
install: 
  - "yarn install"
after_success:
  - 'curl -Lo travis_after_all.py https://git.io/travis_after_all'
  - python travis_after_all.py
  - export $(cat .to_export_back) &> /dev/null
  - npm run coveralls
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
